//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dotn_projekt
{
    using System;
    using System.Collections.Generic;
    
    public partial class raz_odjel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public raz_odjel()
        {
            this.ucenik = new HashSet<ucenik>();
        }
    
        public int id { get; set; }
        public string odjel { get; set; }
        public string nastavnik { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ucenik> ucenik { get; set; }
    }
}
