//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dotn_projekt
{
    using System;
    using System.Collections.Generic;
    
    public partial class ucenik
    {
        public int id { get; set; }
        public string ime { get; set; }
        public string prezime { get; set; }
        public string oib { get; set; }
        public Nullable<int> raz_id { get; set; }
    
        public virtual raz_odjel raz_odjel { get; set; }
    }
}
